fix lint hook

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,6 +1,14 @@
 #!/bin/bash
 
-git diff --cached --name-only --diff-filter=ACM | grep "^app\/media\/js\/.*.js$" | xargs ./node_modules/.bin/eslint
+files=$(git diff --cached --name-only --diff-filter=ACM | grep "^app\/media\/js\/.*.js$")
+
+echo $files | xargs ./node_modules/.bin/eslint
+
+rc=$?
+if [[ $rc != 0 ]] ; then
+	echo "ESLint check failed, commit denied"
+	exit $rc
+fi
 
 git diff --cached --name-only --diff-filter=ACM | if grep "app/jspm.config.js"
 then
